### ISSUE TITLE
Google Slides

### ISSUE THREAD

**Issue by furkanbiten** [antoniRodriguez/MCV-M5-Visual_Recognition#2]
Hi all,

Could you please share your google slides with me? There is a problem in the access.

**Comment by SoftonCV** [comment]
Here you have, 

Sorry for the inconvenience. 

[GoogleSlides](https://drive.google.com/file/d/1NczZXvarT18L7K2T6ER6LL3qt_lhMOoh/view?usp=sharing)

**Comment by furkanbiten** [comment]
Thanks!
